### ISSUE TITLE
big problem

### ISSUE THREAD

**Issue by Paoo2** [VenuzWeeb/Grassware.win-rewrite-BUILDEABLE-SRC-LEAK#2]
It's just gonna get updated and this 'leak' is gonna become outdated very quickly

**Comment by VenuzWeeb** [comment]
im still on his pc so he should factory reset first :)))

**Comment by Paoo2** [comment]
stfk who are you? and VenuzWeeb you aren't, gif logging isn't a thing you just got someone who has access to give you the client
